<a href="https://colab.research.google.com/github/sarathkurapati/ml-dl-notebooks/blob/main/chest_xray_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:

!unzip '/content/drive/MyDrive/chest x ray/chest x ray.zip'

Archive:  /content/drive/MyDrive/chest x ray/chest x ray.zip
replace chest x ray/test/.DS_Store? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [35]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [36]:
train_gen=ImageDataGenerator(rescale=(1./255),horizontal_flip=True,shear_range=0.2)
test_gen=ImageDataGenerator(rescale=(1./255))

In [37]:
train=train_gen.flow_from_directory("/content/chest x ray/train",
                                   target_size=(120,120),
                                   class_mode="categorical",
                                   batch_size=8)
test=test_gen.flow_from_directory("/content/chest x ray/test",
                                  target_size=(120,120),
                                   class_mode="categorical",
                                   batch_size=8)

Found 5216 images belonging to 2 classes.
Found 624 images belonging to 2 classes.


In [38]:
train.class_indices

{'NORMAL': 0, 'PNEUMONIA': 1}

In [43]:
#CNN MODEL BUILDING
from tensorflow.keras.layers import Convolution2D,MaxPooling2D,Flatten,Dense
from tensorflow.keras.models import Sequential

In [61]:
model = Sequential()
model.add(Convolution2D(20,(3,3),activation='relu',input_shape=(120, 120,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(45,activation='relu'))
model.add(Dense(2,activation='softmax'))

In [62]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [63]:
model.fit(train,batch_size=8,validation_data=test,epochs=4)

Epoch 1/4
652/652 [==============================] - 89s 134ms/step - loss: 0.2587 - accuracy: 0.9130 - val_loss: 0.6757 - val_accuracy: 0.7532
Epoch 2/4
652/652 [==============================] - 87s 133ms/step - loss: 0.1011 - accuracy: 0.9632 - val_loss: 0.5566 - val_accuracy: 0.7981
Epoch 3/4
652/652 [==============================] - 83s 127ms/step - loss: 0.0915 - accuracy: 0.9640 - val_loss: 1.3205 - val_accuracy: 0.7019
Epoch 4/4
652/652 [==============================] - 87s 133ms/step - loss: 0.0697 - accuracy: 0.9722 - val_loss: 1.1041 - val_accuracy: 0.7292


In [71]:
import numpy as np
from tensorflow.keras.preprocessing import image

In [72]:
img=image.load_img("/content/test.jpg",target_size=(120,120))
img=image.img_to_array(img)

In [73]:
img=np.expand_dims(img,axis=0)

In [74]:
img

array([[[[  8.,   8.,   8.],
         [  1.,   1.,   1.],
         [  2.,   2.,   2.],
         ...,
         [  2.,   2.,   2.],
         [  0.,   0.,   0.],
         [ 19.,  19.,  19.]],

        [[  8.,   8.,   8.],
         [  1.,   1.,   1.],
         [  1.,   1.,   1.],
         ...,
         [  1.,   1.,   1.],
         [  1.,   1.,   1.],
         [ 16.,  16.,  16.]],

        [[  8.,   8.,   8.],
         [  1.,   1.,   1.],
         [  1.,   1.,   1.],
         ...,
         [  1.,   1.,   1.],
         [  1.,   1.,   1.],
         [ 19.,  19.,  19.]],

        ...,

        [[ 18.,  18.,  18.],
         [  6.,   6.,   6.],
         [  6.,   6.,   6.],
         ...,
         [  1.,   1.,   1.],
         [  8.,   8.,   8.],
         [ 29.,  29.,  29.]],

        [[ 30.,  30.,  30.],
         [ 18.,  18.,  18.],
         [ 19.,  19.,  19.],
         ...,
         [  8.,   8.,   8.],
         [173., 173., 173.],
         [209., 209., 209.]],

        [[ 53.,  53.,  53.],
       

In [75]:
np.argmax(model.predict(img))

1/1 [==============================] - 0s 103ms/step


0

In [80]:
img_1=image.load_img("/content/9451607643d1cd9c4570cdb1c48593_jumbo.jpeg",target_size=(120,120))
img_1=image.img_to_array(img_1)
img_1=np.expand_dims(img_1,axis=0)
img_1

array([[[[234., 234., 234.],
         [229., 229., 229.],
         [228., 228., 228.],
         ...,
         [  4.,   4.,   4.],
         [ 10.,  10.,  10.],
         [  1.,   1.,   1.]],

        [[240., 240., 240.],
         [233., 233., 233.],
         [232., 232., 232.],
         ...,
         [  6.,   6.,   6.],
         [  2.,   2.,   2.],
         [  1.,   1.,   1.]],

        [[237., 237., 237.],
         [229., 229., 229.],
         [228., 228., 228.],
         ...,
         [  4.,   4.,   4.],
         [  1.,   1.,   1.],
         [  1.,   1.,   1.]],

        ...,

        [[255., 255., 253.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[254., 254., 252.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[254., 254., 252.],
       

In [81]:
np.argmax(model.predict(img_1))

1/1 [==============================] - 0s 20ms/step


0

In [82]:
model = Sequential()
model.add(Convolution2D(20,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Convolution2D(40,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Convolution2D(50,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Convolution2D(60,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(45,activation='relu'))
model.add(Dense(55,activation='relu'))
model.add(Dense(65,activation='relu'))
model.add(Dense(2,activation='softmax'))

In [83]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])


In [84]:
model.fit(train,batch_size=8,validation_data=test,epochs=4)


Epoch 1/4
652/652 [==============================] - 88s 129ms/step - loss: 0.3434 - accuracy: 0.8530 - val_loss: 1.1156 - val_accuracy: 0.7404
Epoch 2/4
652/652 [==============================] - 83s 127ms/step - loss: 0.1591 - accuracy: 0.9411 - val_loss: 1.0057 - val_accuracy: 0.7051
Epoch 3/4
652/652 [==============================] - 83s 127ms/step - loss: 0.1251 - accuracy: 0.9486 - val_loss: 1.3512 - val_accuracy: 0.7035
Epoch 4/4
652/652 [==============================] - 84s 129ms/step - loss: 0.1092 - accuracy: 0.9574 - val_loss: 1.1883 - val_accuracy: 0.7356


In [88]:
img3=image.load_img("/content/9451607643d1cd9c4570cdb1c48593_jumbo.jpeg",target_size=(120,120))
img3=image.img_to_array(img3)
img3=np.expand_dims(img3,axis=0)
img3

array([[[[234., 234., 234.],
         [229., 229., 229.],
         [228., 228., 228.],
         ...,
         [  4.,   4.,   4.],
         [ 10.,  10.,  10.],
         [  1.,   1.,   1.]],

        [[240., 240., 240.],
         [233., 233., 233.],
         [232., 232., 232.],
         ...,
         [  6.,   6.,   6.],
         [  2.,   2.,   2.],
         [  1.,   1.,   1.]],

        [[237., 237., 237.],
         [229., 229., 229.],
         [228., 228., 228.],
         ...,
         [  4.,   4.,   4.],
         [  1.,   1.,   1.],
         [  1.,   1.,   1.]],

        ...,

        [[255., 255., 253.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[254., 254., 252.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[254., 254., 252.],
       

In [89]:
np.argmax(model.predict(img3))

1/1 [==============================] - 0s 18ms/step


1

In [90]:
from tensorflow.keras.layers import BatchNormalization,Dropout

In [92]:
model = Sequential()
model.add(Convolution2D(20,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))#values mention o to 1
model.add(Convolution2D(40,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))#values mention o to 1
model.add(Convolution2D(50,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))#values mention o to 1
model.add(Convolution2D(60,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))#values mention o to 1
model.add(Flatten())
model.add(Dense(45,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.1))
model.add(Dense(55,activation='relu'))
model.add(Dense(65,activation='relu'))
model.add(Dense(2,activation='softmax'))

In [93]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])


In [99]:
#early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stop=EarlyStopping(monitor="accuracy",patience=4)

In [100]:
model.fit(train,batch_size=8,validation_data=test,epochs=7,callbacks=early_stop)


Epoch 1/7
652/652 [==============================] - 88s 134ms/step - loss: 0.1406 - accuracy: 0.9482 - val_loss: 0.4173 - val_accuracy: 0.8462
Epoch 2/7
652/652 [==============================] - 89s 136ms/step - loss: 0.1385 - accuracy: 0.9492 - val_loss: 1.2634 - val_accuracy: 0.6458
Epoch 3/7
652/652 [==============================] - 82s 126ms/step - loss: 0.1345 - accuracy: 0.9511 - val_loss: 1.2117 - val_accuracy: 0.7019
Epoch 4/7
652/652 [==============================] - 84s 128ms/step - loss: 0.1333 - accuracy: 0.9542 - val_loss: 0.9967 - val_accuracy: 0.7228
Epoch 5/7
652/652 [==============================] - 82s 126ms/step - loss: 0.1134 - accuracy: 0.9578 - val_loss: 0.3665 - val_accuracy: 0.8686
Epoch 6/7
652/652 [==============================] - 161s 247ms/step - loss: 0.1183 - accuracy: 0.9572 - val_loss: 0.8561 - val_accuracy: 0.6907
Epoch 7/7
652/652 [==============================] - 86s 131ms/step - loss: 0.1171 - accuracy: 0.9553 - val_loss: 0.8870 - val_accuracy

In [101]:
img4=image.load_img("/content/test.jpg",target_size=(120,120))
img4=image.img_to_array(img4)
img4=np.expand_dims(img4,axis=0)
img4
np.argmax(model.predict(img4))

1/1 [==============================] - 0s 159ms/step


1